name: node version print
on:
  push:
    branches:
      - main

jobs:
  install-node:
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        run: actions/checkout@v4
  print-version:
    needs: install-node
    runs-on: ubuntu-latest
    steps:
      - name: print node version
        run: node --version
