name: Build Test and deploy
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test check
        run: echo "Testing..................."

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Buildinggg................"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Deply sucessfully"
