name: node version print
on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  install-node:
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18

  print-version:
    needs: install-node
    runs-on: ubuntu-latest
    steps:
      - name: print node version
        run: node --version
