name: Greeting hello pull the code
# on:
#   push:
#     branches:
#       - main
on:
  pull_request:
    branches:
      - main

jobs:
  greeting-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "The github actor name is $GITHUB_ACTOR"

      - name: Every pr
        run: echo "This is pr request"

  deploy:
    needs: greeting-hello
    runs-on: ubuntu-latest
    steps:
      - name : Is this deploy
        run : echo "Deployment sucessfully"

