name : Hello github action
on:
  push:
    branches:
      - main
jobs:
  hello-jobs:
      runs-on: ubuntu-latest
      steps:
        - name: Print Hello world
          run: echo "Hello World welcome back prince"